import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const soehne = localFont({
  src: [
    {
      path: "./../public/fonts/soehne/soehne-buch.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./../public/fonts/soehne/soehne-buch-kursiv.woff2",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-soehne",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={soehne.variable}>
      <body>
        {children}
      </body>
    </html>
  );
}
